name: CI-CD-Github-Pages-Pipeline

on:
  workflow_call:
  pull_request:
  workflow_dispatch:
  push:
    branches:
      - master

jobs:
  upload-to-github-pages:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    concurrency: ci-cd-${{ github.ref }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Use Node.js 20.17.0
        uses: actions/setup-node@v4
        with: 
          node-version: '20.17.0'

      - name: Install dependencies
        run: npm ci

      - name: Build React app
        run: npm run build

      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: build
          branch: gh-pages